# Generated by Django 4.2.20 on 2025-04-14 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soundBody', '0002_exercise_cv_musician_cv_musician_joindate_trainer_cv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseWorkoutPlan',
            fields=[
                ('baseWorkoutPlanId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomWorkoutPlan',
            fields=[
                ('customWorkoutPlanId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundBody.musician')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundBody.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutCompleteEntry',
            fields=[
                ('workoutCompleteEntryId', models.AutoField(primary_key=True, serialize=False)),
                ('dateCompleted', models.DateField()),
                ('totalDuration', models.IntegerField()),
                ('caloriesBurned', models.IntegerField()),
                ('baseWorkoutPlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soundBody.baseworkoutplan')),
                ('customWorkoutPlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soundBody.customworkoutplan')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundBody.musician')),
            ],
        ),
        migrations.CreateModel(
            name='MusicianWorkoutStatistics',
            fields=[
                ('musicianWorkoutStatisticsId', models.AutoField(primary_key=True, serialize=False)),
                ('totalWorkoutsCompleted', models.IntegerField()),
                ('totalExercisesCompleted', models.IntegerField()),
                ('totalTimeSpent', models.IntegerField()),
                ('averageIntensity', models.CharField(max_length=50)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundBody.musician')),
            ],
        ),
        migrations.CreateModel(
            name='CustomWorkoutPlanExercise',
            fields=[
                ('customWorkoutPlanExerciseId', models.AutoField(primary_key=True, serialize=False)),
                ('sets', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('customWorkoutPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundBody.customworkoutplan')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundBody.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='BaseWorkoutPlanExercise',
            fields=[
                ('baseWorkoutPlanExerciseId', models.AutoField(primary_key=True, serialize=False)),
                ('sets', models.IntegerField()),
                ('repetitions', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('baseWorkoutPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundBody.baseworkoutplan')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundBody.exercise')),
            ],
        ),
    ]
